FROM openjdk:8-jdk-alpine

# Set the working directory to /chord
WORKDIR /chord

# Copy the current directory contents into the container at /src
ADD src /chord/src

#EXPOSE 40000  # client

RUN javac src/*.java

