FROM openjdk:8-jdk-alpine

# Set the working directory to /chord
WORKDIR /chord

# Copy the current directory contents into the container at /src
ADD src/*.java /chord/src/
ADD packet/*.java /chord/packet/

#EXPOSE 30000  # anchor
#EXPOSE 40000  # client

RUN javac src/*.java
